name: control_vacas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.0.9
  shared_preferences: ^2.0.15 
  json_serializable: ^6.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/
